### ISSUE TITLE
unconfigured table schema_keyspaces when cassandra is 3.3

### ISSUE THREAD

**Issue by sallaneh** [inoio/sbt-pillar-plugin#6]
Hi,

I am using Cassandra 3.3
When I try to do anything with the plugin e.g. createKeyspace I get:

`com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))`

But not older version of Cassandra.
Is it related to to [this](http://stackoverflow.com/questions/34117374/com-datastax-driver-core-exceptions-invalidqueryexception-unconfigured-table-sc)?

Regards,
Masood

**Comment by magro** [comment]
Yes, it seems you need PR #5. But I think we can merge and release soon. @MarcoPriebe WDYT?

**Comment by MarcoPriebe** [comment]
I have just released version 2.0.0 where PR #5 is included.
BR,
